# Generated by Django 2.2.5 on 2019-10-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20191026_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscribe',
            field=models.BooleanField(default=False),
        ),
    ]
