# Generated by Django 2.2.5 on 2019-10-25 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20191024_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='report',
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 26, 0, 3, 3, 488763)),
        ),
    ]
